{
	"english": {
		"languagecode": "en",
		"english": "English",
		"finnish": "Suomi",
		"addjob": "New job",
		"add": "Add",
		"id": "ID",
		"name": "Name",
		"email": "Email",
		"phone": "Phone",
		"birthdate": "Date of Birth",
		"country": "Country",
		"gender": "Gender",
		"studyfield": "Field of study",
		"studyyear": "Year of study",
		"jobtypes": "Types of job",
		"skills": "Skills",
		"keywords": "Followed keywords",
		"date": "Date",
		"lastlogin": "Last login",
		"lastip": "Last ip",
		"admin": "Administrator",
		"details": "Click here to view details",
		"delete": "Delete",
		"edit": "Edit",
		"added": "Add date",
		"featured": "(featured)",
		"featureds": "Featured jobs",
		"hidden": "(hidden)",
		"title": "Title",
		"company": "Company",
		"jobtype": "Type of job",
		"jobfield": "Field of job",
		"address": "Address",
		"jobskills": "Required skills",
		"description": "Description",
		"beginning": "Job begins",
		"duration": "Job length",
		"displaydate": "Application deadline",
		"editingjob": "Editing job",
		"save": "Save",
		"addcategory": "New category",
		"category": "Category",
		"editingcategory": "Editing category",
		"editinguser": "Editing user",
		"donotchange": "Do not change, unless necessary!",
		"required": "Required field",
		"format": "Input format",
		"searchby": "Search by",
		"signup": "Signup",
		"login": "Login",
		"logout": "Logout",
		"listalloffers": "List all available offers",
		"welcome": "Welcome",
		"welcometext": "This is where workers and jobs meet!",
		"welcomeback": "Welcome back",
		"home": "Home",
		"findjobs": "Find jobs",
		"about": "About us",
		"sponsor": "Sponsored content",
		"sponsored": "Sponsored content",
		"search": "Search",
		"searchtext": "Search terms...",
		"readmore": "Read more",
		"abouttext": "Lappeenranta University of Technology (LUT) is a pioneering science university in Finland, bringing together the fields of science and business since 1969. Our international community is composed of approximately 6,000 students and experts engaged in scientific research and academic education.",
		"backtotop": "Go back to top",
		"privacy": "Privacy Policy",
		"terms": "Terms of Service",
		"results": "Results",
		"jobs": "Jobs",
		"users": "Users",
		"categories": "Categories",
		"serverlog": "Server log",
		"adduser": "New user",
		"newest": "Newest jobs",
		"formathelp": "Formatting help",
		"descriptiontext": "(Supports various formatting and automatically parses links/images/videos/etc)",
		"editprofile": "Edit profile",
		"editingprofile": "Editing user profile",
		"male": "Male",
		"female": "Female",
		"password": "Password",
		"repeatpassword": "Repeat password",
		"studylevel": "Degree",
		"apply": "Send application",
		"joinus": "Join us!",
		"joinustext": "Register to receive new suitable offers via email.",
		"error": "Error",
		"success": "Success",
		"denied": "Access denied",
		"missing": "Not found",
		"accept": "Accept",
		"fullname": "Firstname Lastname",
		"register": "Register",
		"termstext": "You agree to everything.",
		"privacytext": "You have nothing to hide.",
		"searchbytype": "Search by job type",
		"searchbyfield": "Search by job field",
		"displaydatetext": "Leave empty for default (in 1 month)",
		"other": "Other",
		"forgotpass": "Password reset",
		"submit": "Submit",
		"alreadyexists": "already exists",
		"edited": "edited",
		"added": "added",
		"removed": "removed",
		"undefined": "(not defined)",
		"empty": "(empty)",
		"usernameerror": "Incorrect username",
		"passworderror": "Incorrect password",
		"loginsuccess": "Login successfull",
		"not": "not",
		"user": "User",
		"job": "Job",
		"needlogin": "You have to login first!",
		"invalid": "invalid",
		"passwordtooweak": "Password is too weak (use numbers and letters)",
		"passwordtooshort": "Password is too short (minimum 5 characters)",
		"nextpage": "Next page",
		"prevpage": "Previous page",
		"total": "Total",
		"showing": "Showing results",
		"application": "Application",
		"applicationtext": "Write your application here...",
		"sortmethod": "Sort method",
		"displayDate:desc": "Expiring (inverse)",
		"displayDate:asc": "Expiring",
		"date:desc": "Newest",
		"date:asc": "Oldest",
		"_score:desc": "Relevance",
		"views:desc": "Views",
		"apps:desc": "Favorites",
		"default": "(default)",
		"createdate": "Created",
		"registered": "registered",
		"application": "Application",
		"applications": "Applications",
		"employer": "Employer",
		"noaccess": "No access",
		"update": "Update",
		"unapply": "Remove",
		"today": "Today",
		"closed": "Applications closed",
		"dashboard": "Dashboard",
		"dashboardtext": "This is where employers can manage their job offers and view applications.",
		"sent": "sent",
		"select": "Select",
		"captcha": "Captcha",
		"deleteall": "Remove all search results",
		"received": "received",
		"pleasewait": "Please wait...",
		"addedby": "Added by",
		"reset": "Reset",
		"sensitive": "(Only administrator can see this information)",
		"basicinfo": "Basic information",
		"studiesinfo": "Information about studies",
		"recruitmentinfo": "Recruitment related information",
		"perpage": "per page",
		"upload": "Upload",
		"cv": "CV",
		"uploadcv": "Upload CV",
		"uploads": "Uploaded files",
		"uploaded": "uploaded",
		"document": "Document",
		"documents": "Documents",
		"untranslated": "(No translated version of this document)",
		"notification": "Notification",
		"content": "Content",
		"domain": "domain",
		"notallowed": "not allowed",
		"unverified": "Unverified",
		"unverifiedtext": "Unverified email address, functionality restricted!",
		"verified": "Verified",
		"verifiedtext": "Email address verified. Account activated!",
		"verify": "Verify email address and activate account.",
		"reverify": "Re-send verification email.",
		"favorites": "Favorites",
		"views": "Views",
		"faves": "Favorited",
		"favorite": "Favorite",
		"addfavorite": "Add to favorites",
		"unfavorite": "Remove from favorites",
		"verification": "verification and account activation",
		"manager": "Manager",
		"contactinfo": "Contact information",
		"additional": "Additional information",
		"close": "Close",
		"role": "User role",
		"back": "Back",
		"files": "Files",
		"subscriptioninfo": "Subscription settings",
		"subscribe": "Automatically add new offers to favorites",
		"studysub": "Only notify about jobs of my field of study",
		"recruitsub": "Only notify about jobs of chosen types of jobs",
		"keywordsub": "Only notify about jobs with followed keywords",
		"subscribed": "Subscribed",
		"keywordfollow": "Search term following",
		"emailsub": "Automatically send new offers to my email",
		"accountinfo": "Account information",
		"contactemail": "Contact email",
		"contact": "Contact details",
		"feedbackpage": "Feedback target page",
		"feedbacktext": "Write your feedback here...",
		"optional": "Optional field",
		"feedback": "Feedback",
		"passwordmustmatch": "Passwords must match",
		"updated": "Updated",
		"already": "is already",
		"needverify": "(Only verified users can see this information)",
		"logininfo": "Login information",
		"saved": "saved",
		"public": "(visible to everyone)",
		"userinfo": "User information",
		"emailtext": "After verifying account, you may use another email",
		"jobsettings": "Job offer settings",
		"expired": "(expired)",
		"tracker": "Job offer live tracker",
		"trackernotification": "Job offer live tracker",
		"payment": "Salary",
		"textinput": "Freeform text input"
	},
	"finnish": {
		"languagecode": "fi",
		"english": "English",
		"finnish": "Suomi",
		"addjob": "Uusi ilmoitus",
		"add": "Lisää",
		"id": "ID",
		"name": "Nimi",
		"email": "Sähköposti",
		"phone": "Puhelin",
		"birthdate": "Syntymäpäivä",
		"country": "Maa",
		"gender": "Sukupuoli",
		"studyfield": "Opiskeluala",
		"studyyear": "Opiskeluvuosi",
		"jobtypes": "Työn tyypit",
		"skills": "Osaaminen",
		"keywords": "Seuratut termit",
		"date": "Päivämäärä",
		"lastlogin": "Edellinen kirjautuminen",
		"lastip": "Edellinen ip",
		"admin": "Ylläpitäjä",
		"details": "Klikkaa tästä avataksesi lisätiedot",
		"delete": "Poista",
		"edit": "Muokkaa",
		"added": "Lisäyspäivä",
		"featured": "(tärkeä)",
		"featureds": "Tärkeitä ilmoituksia",
		"hidden": "(piilotettu)",
		"title": "Nimike",
		"company": "Yhtiö",
		"jobtype": "Työn tyyppi",
		"jobfield": "Työn ala",
		"address": "Osoite",
		"jobskills": "Vaadittu osaaminen",
		"description": "Kuvaus",
		"beginning": "Työ alkaa",
		"duration": "Työn kesto",
		"displaydate": "Viimeinen hakupäivä",
		"editingjob": "Muokataan ilmoitusta",
		"save": "Tallenna",
		"addcategory": "Uusi kategoria",
		"category": "Kategoria",
		"editingcategory": "Muokataan kategoriaa",
		"editinguser": "Muokataan käyttäjää",
		"donotchange": "Älä muuta ellei välttämätöntä!",
		"required": "Pakollinen kenttä",
		"format": "Syötteen formaatti",
		"searchby": "Hae",
		"signup": "Registeröidy",
		"login": "Kirjaudu sisään",
		"logout": "Kirjaudu ulos",
		"listalloffers": "Listaa kaikki työt",
		"welcome": "Tervetuloa",
		"welcometext": "Täältä työnantajat ja hakijat löytävät toisensa!",
		"welcomeback": "Tervetuloa takaisin",
		"home": "Etusivu",
		"findjobs": "Hae töitä",
		"about": "Tutustu",
		"sponsor": "Sponsoroitu sisältö",
		"sponsored": "Sponsoroitu sisältö",
		"search": "Haku",
		"searchtext": "Hakutermit...",
		"readmore": "Lue lisää",
		"abouttext": "Lappeenranta University of Technology (LUT) is a pioneering science university in Finland, bringing together the fields of science and business since 1969. Our international community is composed of approximately 6,000 students and experts engaged in scientific research and academic education.",
		"backtotop": "Sivun alkuun",
		"privacy": "Yksityisyys",
		"terms": "Käyttöehdot",
		"results": "Hakutuloksia",
		"jobs": "Työpaikat",
		"users": "Käyttäjät",
		"categories": "Kategoriat",
		"serverlog": "Palvelimen loki",
		"adduser": "Uusi käyttäjä",
		"newest": "Uusimmat työpaikat",
		"formathelp": "Formatointi apu",
		"descriptiontext": "(Tukee monia formaatteja ja automaattisesti tulkkaa linkkejä/videoita/kuvia/muuta)",
		"editprofile": "Muokkaa profiilia",
		"editingprofile": "Muokataan käyttäjän profiilia",
		"male": "Mies",
		"female": "Nainen",
		"password": "Salasana",
		"repeatpassword": "Toista salasana",
		"studylevel": "Tutkinto",
		"apply": "Jätä hakemus",
		"joinus": "Liity meihin!",
		"joinustext": "Rekisteröidy saadaksesi uusimmat työpaikka ilmoitukset sähköpostitse.",
		"error": "Virhe",
		"success": "Onnistuminen",
		"denied": "Pääsy estetty",
		"missing": "Ei löydy",
		"accept": "Hyväksy",
		"fullname": "Etunimi Sukunimi",
		"register": "Rekisteröidy",
		"termstext": "Hyväksyt kaiken.",
		"privacytext": "Sinulla ei ole salattavaa.",
		"searchbytype": "Hae tyypin perusteella",
		"searchbyfield": "Hae alan perusteella",
		"displaydatetext": "Jätä tyhjäksi käyttääkseen vakioarvoa (kuukauden kuluttua)",
		"other": "Muu",
		"forgotpass": "Salasanan palautus",
		"submit": "Lähetä",
		"alreadyexists": "on jo olemassa",
		"edited": "muokattu",
		"added": "lisätty",
		"removed": "poistettu",
		"undefined": "(ei määritelty)",
		"empty": "(tyhjä)",
		"usernameerror": "Virheellinen käyttäjä",
		"passworderror": "Virheellinen salasana",
		"loginsuccess": "Sisäänkirjautuminen onnistui",
		"not": "ei",
		"user": "Käyttäjä",
		"job": "Ilmoitus",
		"needlogin": "Sinun täytyy kirjautua ensin!",
		"invalid": "virheellinen",
		"passwordtooweak": "Salasana on liian heikko (käytä numeroita ja kirjaimia)",
		"passwordtooshort": "Salasana on liian lyhyt (minimissään 5 merkkiä)",
		"nextpage": "Seuraava sivu",
		"prevpage": "Edellinen sivu",
		"total": "Yhteensä",
		"showing": "Näytetään tulokset",
		"application": "Hakemus",
		"applicationtext": "Kirjoita hakemuksesi tähän...",
		"sortmethod": "Järjestys",
		"displayDate:desc": "Umpeutuvat (käänteinen)",
		"displayDate:asc": "Umpeutuvat",
		"date:desc": "Uusimmat",
		"date:asc": "Vanhimmat",
		"_score:desc": "Relevanttius",
		"views:desc": "Katselukerrat",
		"apps:desc": "Suosikit",
		"default": "(vakio)",
		"createdate": "Luotu",
		"registered": "rekisteröity",
		"application": "Hakemus",
		"applications": "Hakemukset",
		"employer": "Työnantaja",
		"noaccess": "Ei oikeuksia",
		"update": "Päivitä",
		"unapply": "Poista",
		"today": "Tänään",
		"closed": "Haku päättynyt",
		"dashboard": "Hallintapaneeli",
		"dashboardtext": "Täältä työnantajat voivat hallita ilmoituksiaan ja nähdä vastaanotettuja hakemuksia.",
		"sent": "lähetetty",
		"select": "Valitse",
		"captcha": "Captcha",
		"deleteall": "Poista kaikki haetut tulokset",
		"received": "vastaanotettu",
		"pleasewait": "Odota hetki...",
		"addedby": "Lisääjä",
		"reset": "Nollaa",
		"sensitive": "(Vain ylläpitäjä näkee nämä tiedot)",
		"basicinfo": "Perustiedot",
		"studiesinfo": "Opintoihin liittyvät tiedot",
		"recruitmentinfo": "Työnhakuun liittyvät tiedot",
		"perpage": "per sivu",
		"upload": "Lataa",
		"cv": "CV",
		"uploadcv": "Lataa CV",
		"uploads": "Ladatut tiedostot",
		"uploaded": "ladattu",
		"document": "Dokumentti",
		"documents": "Dokumentit",
		"untranslated": "(Ei käännettyä versiota tästä dokumentista)",
		"notification": "Ilmoitus",
		"content": "Sisältö",
		"domain": "pääte",
		"notallowed": "ei sallittu",
		"unverified": "Ei aktivoitu",
		"unverifiedtext": "Varmistamaton sähköpostiosoite, toiminnot rajattuja!",
		"verified": "Verifiotu",
		"verifiedtext": "Sähköposti varmistettu. Käyttäjä aktivoitu!",
		"verify": "Verifioi sähköpostiosoite ja aktivoi käyttäjä.",
		"reverify": "Uudelleenlähetä varmistus sähköposti.",
		"favorites": "Suosikit",
		"views": "Katselukerrat",
		"faves": "Suosikit",
		"favorite": "Suosikki",
		"addfavorite": "Lisää suosikkeihin",
		"unfavorite": "Poista suosikeista",
		"verification": "varmennus ja tunnuksen aktivointi",
		"manager": "Hallinnoija",
		"contactinfo": "Yhteystiedot",
		"additional": "Lisätiedot",
		"close": "Sulje",
		"role": "Käyttäjän rooli",
		"back": "Takaisin",
		"files": "Tiedostot",
		"subscriptioninfo": "Seuranta asetukset",
		"subscribe": "Automaattisesti lisää uudet ilmoitukset suosikkeihin",
		"studysub": "Seuraa vain oman alan ilmoituksia",
		"recruitsub": "Seuraa vain valittuja työn tyyppejä",
		"keywordsub": "Seuraa vain ilmoituksia, jotka sisältää syötetyt hakutermit",
		"subscribed": "Seurataan",
		"keywordfollow": "Hakusanojen seuranta",
		"emailsub": "Automaattisesti lähetä uudet ilmoitukset sähköpostiini",
		"account": "Käyttäjätiedot",
		"contactemail": "Yhteydenotto email",
		"contact": "Yhteystiedot",
		"feedbackpage": "Palautteen kohdesivusto",
		"feedbacktext": "Kirjoita palaute tähän...",
		"optional": "Vaihtoehtoinen kenttä",
		"feedback": "Palaute",
		"passwordmustmatch": "Salasanojen on täsmättävä",
		"updated": "Päivitetty",
		"already": "on jo",
		"needverify": "(Vain varmistetut käyttäjät näkee nämä tiedot)",
		"logininfo": "Kirjautumistiedot",
		"saved": "tallennettu",
		"public": "(näkyy kaikille)",
		"userinfo": "Käyttäjän tiedot",
		"emailtext": "Varmistuksen jälkeen voit käyttää toista sähköpostia",
		"jobsettings": "Ilmoituksen asetukset",
		"expired": "(päättynyt)",
		"tracker": "Ilmoitusten live seuranta",
		"trackernotification": "Ilmoitusten live seuranta",
		"payment": "Palkka",
		"textinput": "Vapaamuotoinen tekstisyöte"
	}
}