{
	"english": {
		"english": "English",
		"finnish": "Suomi",
		"addjob": "Add new job",
		"add": "Add",
		"id": "ID",
		"name": "Name",
		"email": "Email",
		"phone": "Phone",
		"birthdate": "Date of Birth",
		"country": "Country",
		"gender": "Gender",
		"studyfield": "Field of study",
		"studyyear": "Year of study",
		"jobtypes": "Types of job",
		"skills": "Skills",
		"keywords": "Followed keywords",
		"date": "Date",
		"lastlogin": "Last login",
		"lastip": "Last ip",
		"admin": "Administrator",
		"details": "Details",
		"delete": "Delete",
		"edit": "Edit",
		"added": "Add date",
		"featured": "Featured",
		"hidden": "Hidden",
		"title": "Title",
		"company": "Company",
		"jobtype": "Type of job",
		"jobfield": "Field of job",
		"address": "Address",
		"jobskills": "Required skills",
		"description": "Description",
		"beginning": "Job begins",
		"duration": "Job length",
		"displaydate": "Expiry date",
		"editingjob": "Editing job",
		"save": "Save",
		"addcategory": "Add category",
		"category": "Category",
		"editingcategory": "Editing category",
		"editinguser": "Editing user",
		"donotchange": "Do not change, unless necessary!",
		"required": "Required field",
		"format": "Input format",
		"searchby": "Search by",
		"signup": "Signup",
		"login": "Login",
		"logout": "Logout",
		"listalloffers": "List all available offers",
		"welcome": "Welcome",
		"welcometext": "This is where workers and jobs meet!",
		"welcomeback": "Welcome back",
		"home": "Home",
		"findjobs": "Find jobs",
		"about": "About us",
		"sponsor": "Sponsored content",
		"search": "Search",
		"searchtext": "Search terms...",
		"readmore": "Read more",
		"abouttext": "Lappeenranta University of Technology (LUT) is a pioneering science university in Finland, bringing together the fields of science and business since 1969. Our international community is composed of approximately 6,000 students and experts engaged in scientific research and academic education.",
		"backtotop": "Go back to top",
		"privacy": "Privacy Policy",
		"terms": "Terms of Service",
		"results": "Number of results",
		"jobs": "Jobs",
		"users": "Users",
		"categories": "Categories",
		"serverlog": "Server log",
		"adduser": "Add user",
		"newest": "Newest",
		"formathelp": "Formatting help",
		"descriptiontext": "(Supports various formatting and automatically parses links/images/videos/etc)",
		"editprofile": "Edit profile",
		"editingprofile": "Editing user profile",
		"male": "Male",
		"female": "Female",
		"password": "Password",
		"repeatpassword": "Repeat password",
		"studylevel": "Degree"
	},
	"finnish": {
		"english": "English",
		"finnish": "Suomi"
	}
}