{
	"english": {
		"english": "English",
		"finnish": "Suomi",
		"addjob": "Add new job",
		"add": "Add",
		"id": "ID",
		"name": "Name",
		"email": "Email",
		"phone": "Phone",
		"birthdate": "Date of Birth",
		"country": "Country",
		"gender": "Gender",
		"studyfield": "Field of study",
		"studyyear": "Year of study",
		"jobtypes": "Types of job",
		"skills": "Skills",
		"keywords": "Followed keywords",
		"date": "Date",
		"lastlogin": "Last login",
		"lastip": "Last ip",
		"admin": "Administrator",
		"details": "Details",
		"delete": "Delete",
		"edit": "Edit",
		"added": "Add date",
		"featured": "Featured",
		"hidden": "Hidden",
		"title": "Title",
		"company": "Company",
		"jobtype": "Type of job",
		"jobfield": "Field of job",
		"address": "Address",
		"jobskills": "Required skills",
		"description": "Description",
		"beginning": "Job begins",
		"duration": "Job length",
		"displaydate": "Expiry date",
		"editingjob": "Editing job",
		"save": "Save",
		"addcategory": "Add category",
		"category": "Category",
		"editingcategory": "Editing category",
		"editinguser": "Editing user",
		"donotchange": "Do not change, unless necessary!",
		"required": "Required field",
		"format": "Input format",
		"searchby": "Search by",
		"signup": "Signup",
		"login": "Login",
		"listalloffers": "List all available offers",
		"welcome": "Welcome",
		"welcometext": "This is where workers and jobs meet!"
	},
	"finnish": {
		"english": "English",
		"finnish": "Suomi"
	}
}